### ISSUE TITLE
Første utkast av Token-struktur for farger

### ISSUE THREAD

**Issue by trybern** [FHIDev/Fhi.Designsystem#56]
### Description

Vi må få på plass en hovedstruktur for Design Tokens som vi kan bruke på komponentene vi nå skal mekke. I denne omgang vil fokuset være på farger.

### Acceptance Criteria

- Ryddig oppstilling av Design Tokens i Figma

### Additional information

- #6 brukes som eksempel/test for dette. Det fordrer, i tillegg til farger, noen tokens for spacing og tekst.

**Comment by trybern** [comment]
[Her er forslaget til fargesystem](https://www.figma.com/design/VgQG6XeEbFOmHIrxyAOACR/FHI-Designsystem-TEST?node-id=277-8926&node-type=canvas&t=QQGhOZxoIOVoWSfO-11)

Per nå henter det semantiske laget fra et sett med primitive fargeskalaer. Disse er basert på FHIs veileder for visuell profil og regnet ut på tilsvarende måte som statistikkpaletten vår.

---

Noterer ned litt som tas i egen saker:

1. Primitive fargers grunnverdier (aka. HEX-kodene) må gjennomgås en ekstra gang, for å sørge for konsekvent kontrast mellom de forskjellige stegene. Noen av verdiene til det semantiske laget kan være blir justert opp eller ned, avhengig av kontrastkravene vi har til blant annet tekst.
2. I dag bruker _Accent_ og _Info_ samme farge, noe som gir _Accent_ mindre effekt og _Info_ mer enn det burde ha. Her bør vi skille, for eksempel ved å skille [dagens blå fra visuell veileder](https://www.fhi.no/om/fhi/visuell-profil/innhold/farger/?term=) i lilla og blå.
3. Farger for branding/merkevare må ses sammen med strategier hos Kommunikasjon/Visuelt.
4. Vi kan vurdere flere Neutral-skaler (per nå baserer vi oss på "blågrå", mens ["greige"](https://www.fhi.no/om/fhi/visuell-profil/innhold/farger/?term=) også er en tillatt FHI-farge), dersom det er et behov for å uttrykke andre toner. Dette sees i sammenheng med nr. 3.

**Comment by proand** [comment]
@trybern  Dette systemet ser solid ut så vidt jeg kan se. Semantikken er god; lett å forstå alle navn som er brukt. Godkjent fra min side 👍

**Comment by proand** [comment]
Djevelen og detaljene... går litt grundigere til verks i forbindelse med #69, og lurer på "Blue Gray" vs. "Grey Blue": kunne de vært navnet likt?

**Comment by trybern** [comment]
> Jeg ser at det er tokens for black og white. Har du vurdert en gråskala i steden? I så fall, hvorfor valgte du black/white fremfor gråskala?

Disse brukes som konstante, "rene" farger, tilsvarende verdier som "none" for `spacing`-tokens og "full" på `border-radius`. Neutral fungerer som gråskala slik det er satt opp. 

> Djevelen og detaljene... går litt grundigere til verks i forbindelse med https://github.com/FHIDev/Fhi.Designsystem/pull/69, og lurer på "Blue Gray" vs. "Grey Blue": kunne de vært navnet likt?

Enig at vi skal være konsekvente i navnegivningen. Tenker vi kan holde oss til Grey Blue, som vil være konsekvent med [FHIs veileder for visuelle profil](https://arc.net/l/quote/oubbsczi).
